// Mocks generated by Mockito 5.4.4 from annotations
// in todo_project/test/features/tasks/providers/task_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_project/data/database/database.dart' as _i6;
import 'package:todo_project/data/models/importance_level.dart' as _i4;
import 'package:todo_project/data/models/notification_type.dart' as _i8;
import 'package:todo_project/data/models/task_status.dart' as _i5;
import 'package:todo_project/data/repositories/todo_repository.dart' as _i2;
import 'package:todo_project/features/tasks/providers/notification_providers.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> createTodo({
    required String? title,
    String? description,
    required _i4.ImportanceLevel? importance,
    _i5.TaskStatus? status = _i5.TaskStatus.notStarted,
    DateTime? dueDate,
    List<DateTime>? reminders,
    List<int>? tagIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTodo,
          [],
          {
            #title: title,
            #description: description,
            #importance: importance,
            #status: status,
            #dueDate: dueDate,
            #reminders: reminders,
            #tagIds: tagIds,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i6.TodoTask>> getAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #getAllTodos,
          [],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<_i6.TodoTask?> getTodoById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTodoById,
          [id],
        ),
        returnValue: _i3.Future<_i6.TodoTask?>.value(),
      ) as _i3.Future<_i6.TodoTask?>);

  @override
  _i3.Future<_i6.TodoTask?> getTodoByUuid(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #getTodoByUuid,
          [uuid],
        ),
        returnValue: _i3.Future<_i6.TodoTask?>.value(),
      ) as _i3.Future<_i6.TodoTask?>);

  @override
  _i3.Stream<List<_i6.TodoTask>> watchAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #watchAllTodos,
          [],
        ),
        returnValue: _i3.Stream<List<_i6.TodoTask>>.empty(),
      ) as _i3.Stream<List<_i6.TodoTask>>);

  @override
  _i3.Stream<_i6.TodoTask?> watchTodoByUuid(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTodoByUuid,
          [uuid],
        ),
        returnValue: _i3.Stream<_i6.TodoTask?>.empty(),
      ) as _i3.Stream<_i6.TodoTask?>);

  @override
  _i3.Future<List<_i6.TodoTask>> getTodosDueToday() => (super.noSuchMethod(
        Invocation.method(
          #getTodosDueToday,
          [],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<List<_i6.TodoTask>> getOverdueTodos() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueTodos,
          [],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<List<_i6.TodoTask>> getTodosByImportance(
          _i4.ImportanceLevel? importance) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodosByImportance,
          [importance],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<List<_i6.TodoTask>> getTodosByStatus(_i5.TaskStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodosByStatus,
          [status],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<List<_i6.TodoTask>> getCompletedTodos() => (super.noSuchMethod(
        Invocation.method(
          #getCompletedTodos,
          [],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<List<_i6.TodoTask>> getIncompleteTodos() => (super.noSuchMethod(
        Invocation.method(
          #getIncompleteTodos,
          [],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<List<_i6.TodoTask>> getTodosByTag(int? tagId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodosByTag,
          [tagId],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<List<_i6.TodoTask>> searchTodos(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTodos,
          [query],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<bool> updateTodo(
    int? id, {
    String? title,
    String? description,
    _i4.ImportanceLevel? importance,
    _i5.TaskStatus? status,
    DateTime? dueDate,
    List<DateTime>? reminders,
    DateTime? reminderDateTime,
    bool? isCompleted,
    DateTime? completedAt,
    bool? isDueToday,
    bool? isOverdue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [id],
          {
            #title: title,
            #description: description,
            #importance: importance,
            #status: status,
            #dueDate: dueDate,
            #reminders: reminders,
            #reminderDateTime: reminderDateTime,
            #isCompleted: isCompleted,
            #completedAt: completedAt,
            #isDueToday: isDueToday,
            #isOverdue: isOverdue,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i6.TaskReminder>> getReminders(int? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReminders,
          [taskId],
        ),
        returnValue:
            _i3.Future<List<_i6.TaskReminder>>.value(<_i6.TaskReminder>[]),
      ) as _i3.Future<List<_i6.TaskReminder>>);

  @override
  _i3.Stream<List<_i6.TaskReminder>> watchReminders(int? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchReminders,
          [taskId],
        ),
        returnValue: _i3.Stream<List<_i6.TaskReminder>>.empty(),
      ) as _i3.Stream<List<_i6.TaskReminder>>);

  @override
  _i3.Future<void> addReminder(
    int? taskId,
    DateTime? scheduledAt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReminder,
          [
            taskId,
            scheduledAt,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeReminder(int? reminderId) => (super.noSuchMethod(
        Invocation.method(
          #removeReminder,
          [reminderId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> completeTodo(int? taskId) => (super.noSuchMethod(
        Invocation.method(
          #completeTodo,
          [taskId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> uncompleteTodo(int? taskId) => (super.noSuchMethod(
        Invocation.method(
          #uncompleteTodo,
          [taskId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> addTagToTodo(
    int? taskId,
    int? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTagToTodo,
          [
            taskId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeTagFromTodo(
    int? taskId,
    int? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagFromTodo,
          [
            taskId,
            tagId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> deleteTodo(int? taskId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodo,
          [taskId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteTodoByUuid(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodoByUuid,
          [uuid],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteCompletedTodos() => (super.noSuchMethod(
        Invocation.method(
          #deleteCompletedTodos,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllTodos,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getTodoCount() => (super.noSuchMethod(
        Invocation.method(
          #getTodoCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getCompletedCount() => (super.noSuchMethod(
        Invocation.method(
          #getCompletedCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getIncompleteCount() => (super.noSuchMethod(
        Invocation.method(
          #getIncompleteCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getOverdueCount() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getTodayCount() => (super.noSuchMethod(
        Invocation.method(
          #getTodayCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> createRecurringTask({
    required String? title,
    required _i4.ImportanceLevel? importance,
    required int? recurringPatternId,
    String? description,
    String? seriesId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRecurringTask,
          [],
          {
            #title: title,
            #importance: importance,
            #recurringPatternId: recurringPatternId,
            #description: description,
            #seriesId: seriesId,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i6.TodoTask>> getRecurringTemplates() => (super.noSuchMethod(
        Invocation.method(
          #getRecurringTemplates,
          [],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<List<_i6.TodoTask>> getRecurringInstances(String? seriesId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecurringInstances,
          [seriesId],
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<_i6.TodoTask?> getRecurringTemplate(String? seriesId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecurringTemplate,
          [seriesId],
        ),
        returnValue: _i3.Future<_i6.TodoTask?>.value(),
      ) as _i3.Future<_i6.TodoTask?>);

  @override
  _i3.Future<void> updateEntireSeries(
    String? seriesId, {
    String? title,
    String? description,
    _i4.ImportanceLevel? importance,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntireSeries,
          [seriesId],
          {
            #title: title,
            #description: description,
            #importance: importance,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateFutureInstances(
    int? fromInstanceId, {
    String? title,
    String? description,
    _i4.ImportanceLevel? importance,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFutureInstances,
          [fromInstanceId],
          {
            #title: title,
            #description: description,
            #importance: importance,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> deleteEntireSeries(String? seriesId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntireSeries,
          [seriesId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteFutureInstances(int? fromInstanceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFutureInstances,
          [fromInstanceId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> skipInstance(int? instanceId) => (super.noSuchMethod(
        Invocation.method(
          #skipInstance,
          [instanceId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> postponeInstance(
    int? instanceId,
    DateTime? newDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postponeInstance,
          [
            instanceId,
            newDate,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> cleanupOldInstances({int? daysToKeep = 30}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupOldInstances,
          [],
          {#daysToKeep: daysToKeep},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Stream<List<_i6.TodoTask>> watchRecurringTemplates() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRecurringTemplates,
          [],
        ),
        returnValue: _i3.Stream<List<_i6.TodoTask>>.empty(),
      ) as _i3.Stream<List<_i6.TodoTask>>);

  @override
  _i3.Future<List<_i6.TodoTask>> getUpcomingInstances(
    String? seriesId, {
    int? count = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingInstances,
          [seriesId],
          {#count: count},
        ),
        returnValue: _i3.Future<List<_i6.TodoTask>>.value(<_i6.TodoTask>[]),
      ) as _i3.Future<List<_i6.TodoTask>>);

  @override
  _i3.Future<int> bulkComplete(List<int>? taskIds) => (super.noSuchMethod(
        Invocation.method(
          #bulkComplete,
          [taskIds],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> bulkDelete(List<int>? taskIds) => (super.noSuchMethod(
        Invocation.method(
          #bulkDelete,
          [taskIds],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> bulkUpdateImportance(
    List<int>? taskIds,
    _i4.ImportanceLevel? importance,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkUpdateImportance,
          [
            taskIds,
            importance,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> bulkAddTag(
    List<int>? taskIds,
    int? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkAddTag,
          [
            taskIds,
            tagId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> bulkRemoveTag(
    List<int>? taskIds,
    int? tagId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkRemoveTag,
          [
            taskIds,
            tagId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [TaskNotificationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskNotificationManager extends _i1.Mock
    implements _i7.TaskNotificationManager {
  MockTaskNotificationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> scheduleTaskNotifications(
    _i6.TodoTask? task, {
    List<DateTime>? customReminders,
    Map<DateTime, _i8.NotificationType>? reminderTypes,
    _i8.NotificationType? dueDateNotificationType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleTaskNotifications,
          [task],
          {
            #customReminders: customReminders,
            #reminderTypes: reminderTypes,
            #dueDateNotificationType: dueDateNotificationType,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelTaskNotifications(int? taskId) => (super.noSuchMethod(
        Invocation.method(
          #cancelTaskNotifications,
          [taskId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> notifyOverdue(_i6.TodoTask? task) => (super.noSuchMethod(
        Invocation.method(
          #notifyOverdue,
          [task],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
